### ISSUE TITLE
新浪博客现在已经不对外开放了，只能自己看到文章和照片。

### ISSUE THREAD

**Issue by mxxba** [apqx/AutoTools#1]
不知道大佬能不能针对这种情况改进一下代码呀，小白一枚，急需备份自己的博客内容。

**Comment by apqx** [comment]
抱歉这只是一个新浪博客的图片下载工具，初衷是为了方便下载文章中大量的原始照片，尤其针对博主分享的舞台剧照，并不提供下载博文的功能。我理解新浪博客可能很快会停止服务，建议用其它方式尽快保存需要保存的博客文章（比如手动复制文本到本地文件，或者使用类似印象笔记会提供的“剪切”功能来保存文章内容到笔记文档中）。

**Comment by apqx** [comment]
可能我理解错了，我刚刚才发现打开之前保存的新浪博客链接会显示“系统维护中，博文仅作者可见，登录后可查看本人文章”，确实如你所说现在只有作者才能访问到博客内容，即这个图片下载工具在这种情况下是失效的。我没有新浪博客的账号，现在新浪也不允许注册，不清楚新浪是如何携带用户登录信息的，所以不知道如何在代码中实现新浪博客的「登录」。

**Comment by mxxba** [comment]
谢谢回复，只能这样了。祝你一切顺利。
